language: c
cache:
  directories:
    - "$HOME/cache"
compiler:
  - gcc
sudo: false
script: ./test/travis/script.sh
notifications:
  email:
    on_success: never
    on_failure: never
  irc: "irc://chat.freenode.net/#libsuola"
  use_notice: true
env:
  - "OPENSSL_VERSION=1.0.2 DEBIAN_PACKAGES='http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu4.13_amd64.deb http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/openssl_1.0.2g-1ubuntu4.13_amd64.deb http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/libssl-dev_1.0.2g-1ubuntu4.13_amd64.deb'"
  - "OPENSSL_VERSION=1.1.0 DEBIAN_PACKAGES='http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4.1_amd64.deb http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/openssl_1.1.0g-2ubuntu4.1_amd64.deb http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/libssl-dev_1.1.0g-2ubuntu4.1_amd64.deb'"
  - OPENSSL_VERSION=master
matrix:
  allow_failures:
    - env: "OPENSSL_VERSION=1.0.2 DEBIAN_PACKAGES='http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu4.13_amd64.deb http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/openssl_1.0.2g-1ubuntu4.13_amd64.deb http://ftp.fi.debian.org/ubuntu/pool/main/o/openssl/libssl-dev_1.0.2g-1ubuntu4.13_amd64.deb'"
addons:
  apt:
    packages:
      - cmake
      - xz-utils
